{% set version = "13.7.0" %}

package:
  name: mpxj
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/mpxj/mpxj-{{ version }}.tar.gz
  sha256: 2af8ad389bdfdf90358019096ed336658f896b48d6bc30f8b80ea36fe65f752c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - jpype1
    - openjdk

test:
  imports:
    - mpxj
  commands:
    - python -c "import jpype; import mpxj; jpype.startJVM(convertStrings=False); ProjectFile = jpype.JClass('net.sf.mpxj.ProjectFile')"

about:
  home: https://www.mpxj.org/
  summary: Python wrapper for the MPXJ Java library for manipulating project files
  dev_url: https://github.com/joniles/mpxj
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jschueller
