{% set version = "12.6.0" %}

package:
  name: mpxj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mpxj/mpxj-{{ version }}.tar.gz
  sha256: 9539dbae59cf5c74138c5ab3965332739299a029a1a2350a5030bda9dd2c072d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jpype1
    - openjdk

test:
  imports:
    - mpxj
  commands:
    - python -c "import jpype; import mpxj; jpype.startJVM(convertStrings=False); ProjectFile = jpype.JClass('net.sf.mpxj.ProjectFile')"

about:
  home: https://www.mpxj.org/
  summary: Python wrapper for the MPXJ Java library for manipulating project files
  dev_url: https://github.com/joniles/mpxj
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jschueller
