{% set version = "13.11.0" %}

package:
  name: mpxj
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/mpxj/mpxj-{{ version }}.tar.gz
  sha256: b50c1f1cc42be4580eb90e004209d3915f933b9615d9186e2ae2d05f0f9174b3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - jpype1
    - openjdk

test:
  requires:
    - python {{ python_min }}
  imports:
    - mpxj
  commands:
    - python -c "import jpype; import mpxj; jpype.startJVM(convertStrings=False); ProjectFile = jpype.JClass('net.sf.mpxj.ProjectFile')"

about:
  home: https://www.mpxj.org/
  summary: Python wrapper for the MPXJ Java library for manipulating project files
  dev_url: https://github.com/joniles/mpxj
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jschueller
