{% set version = "13.8.0" %}

package:
  name: mpxj
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/mpxj/mpxj-{{ version }}.tar.gz
  sha256: 265b0b1e33ac7bfbd265c49ce5c03f4c13d20655c9232e58cad7280e646a471f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - jpype1
    - openjdk

test:
  imports:
    - mpxj
  commands:
    - python -c "import jpype; import mpxj; jpype.startJVM(convertStrings=False); ProjectFile = jpype.JClass('net.sf.mpxj.ProjectFile')"

about:
  home: https://www.mpxj.org/
  summary: Python wrapper for the MPXJ Java library for manipulating project files
  dev_url: https://github.com/joniles/mpxj
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jschueller
